services:
- type: web
  name: cosmic-omni-brain-ai
  env: python
  repo: https://github.com/your-username/cosmic-omni-brain-ai.git
  buildCommand: pip install -r requirements.txt
  startCommand: python app.py
  plan: free
  healthCheckPath: /health
  envVars:
  - key: FLASK_ENV
    value: production
  - key: TELEGRAM_BOT_TOKEN
    sync: false
  - key: TELEGRAM_CHAT_ID
    sync: false
